# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e0b0d14502aed8d4edf3c1eff5da37c1f6f032d490d6cbfa8d93f28130dfd8865954a6bb22ce28b439b6f59e6b7b234b013fa784a5254366a3b2efba2b679f

test:
  secret_key_base: b137b7c1f09e66c645f8c4da749876fb3bc4df9f4af7e105e47de6bf35aecabb7012d2417c51fbfb07107222a7bf750d324ab9e1e6eebe3fdc99b174bfb7ce1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
