Assignment.create!([
  {task_id: 61, asignee_id: 14},
  {task_id: 62, asignee_id: 14},
  {task_id: 65, asignee_id: 14},
  {task_id: 66, asignee_id: 14},
  {task_id: 67, asignee_id: 14},
  {task_id: 68, asignee_id: 1},
  {task_id: 70, asignee_id: 1},
  {task_id: 71, asignee_id: 14},
  {task_id: 72, asignee_id: 14},
  {task_id: 76, asignee_id: 5},
  {task_id: 83, asignee_id: 14},
  {task_id: 109, asignee_id: 14},
  {task_id: 112, asignee_id: 14},
  {task_id: 113, asignee_id: 14},
  {task_id: 114, asignee_id: 14},
  {task_id: 115, asignee_id: 14},
  {task_id: 116, asignee_id: 14},
  {task_id: 117, asignee_id: 14},
  {task_id: 119, asignee_id: 14},
  {task_id: 120, asignee_id: 14},
  {task_id: 121, asignee_id: 14},
  {task_id: 122, asignee_id: 14},
  {task_id: 123, asignee_id: 14},
  {task_id: 125, asignee_id: 14},
  {task_id: 126, asignee_id: 14},
  {task_id: 127, asignee_id: 14},
  {task_id: 128, asignee_id: 14},
  {task_id: 130, asignee_id: 14},
  {task_id: 131, asignee_id: 14},
  {task_id: 132, asignee_id: 14},
  {task_id: 133, asignee_id: 14},
  {task_id: 134, asignee_id: 14},
  {task_id: 135, asignee_id: 14},
  {task_id: 136, asignee_id: 14},
  {task_id: 137, asignee_id: 14},
  {task_id: 138, asignee_id: 14},
  {task_id: 139, asignee_id: 14},
  {task_id: 140, asignee_id: 14},
  {task_id: 141, asignee_id: 14},
  {task_id: 142, asignee_id: 14},
  {task_id: 143, asignee_id: 14},
  {task_id: 144, asignee_id: 14},
  {task_id: 145, asignee_id: 14},
  {task_id: 146, asignee_id: 14},
  {task_id: 147, asignee_id: 14},
  {task_id: 148, asignee_id: 14},
  {task_id: 149, asignee_id: 14},
  {task_id: 150, asignee_id: 14},
  {task_id: 151, asignee_id: 14},
  {task_id: 152, asignee_id: 14},
  {task_id: 153, asignee_id: 14},
  {task_id: 154, asignee_id: 14},
  {task_id: 155, asignee_id: 14},
  {task_id: 156, asignee_id: 14},
  {task_id: 158, asignee_id: 14},
  {task_id: 159, asignee_id: 14},
  {task_id: 160, asignee_id: 14},
  {task_id: 161, asignee_id: 14},
  {task_id: 162, asignee_id: 14},
  {task_id: 164, asignee_id: 14},
  {task_id: 165, asignee_id: 14},
  {task_id: 166, asignee_id: 14},
  {task_id: 167, asignee_id: 14},
  {task_id: 169, asignee_id: 14},
  {task_id: 172, asignee_id: 14},
  {task_id: 173, asignee_id: 14},
  {task_id: 174, asignee_id: 6},
  {task_id: 175, asignee_id: 0},
  {task_id: 176, asignee_id: 0},
  {task_id: 177, asignee_id: 0},
  {task_id: 178, asignee_id: 14},
  {task_id: 179, asignee_id: 0},
  {task_id: 187, asignee_id: 7},
  {task_id: 190, asignee_id: 6},
  {task_id: 191, asignee_id: 1},
  {task_id: 192, asignee_id: 9},
  {task_id: 193, asignee_id: 9},
  {task_id: 194, asignee_id: 7},
  {task_id: 196, asignee_id: 5},
  {task_id: 196, asignee_id: 14},
  {task_id: 197, asignee_id: 14},
  {task_id: 198, asignee_id: 6},
  {task_id: 199, asignee_id: 1},
  {task_id: 199, asignee_id: 6},
  {task_id: 200, asignee_id: 14},
  {task_id: 201, asignee_id: 1},
  {task_id: 201, asignee_id: 6},
  {task_id: 202, asignee_id: 1},
  {task_id: 202, asignee_id: 5},
  {task_id: 203, asignee_id: 1},
  {task_id: 203, asignee_id: 6},
  {task_id: 203, asignee_id: 5},
  {task_id: 203, asignee_id: 7},
  {task_id: 204, asignee_id: 1},
  {task_id: 204, asignee_id: 6},
  {task_id: 205, asignee_id: 14},
  {task_id: 205, asignee_id: 5},
  {task_id: 206, asignee_id: 14},
  {task_id: 207, asignee_id: 14},
  {task_id: 208, asignee_id: 14},
  {task_id: 209, asignee_id: 14},
  {task_id: 210, asignee_id: 14},
  {task_id: 211, asignee_id: 14},
  {task_id: 212, asignee_id: 1},
  {task_id: 212, asignee_id: 6},
  {task_id: 212, asignee_id: 5},
  {task_id: 213, asignee_id: 1},
  {task_id: 213, asignee_id: 5},
  {task_id: 213, asignee_id: 6},
  {task_id: 214, asignee_id: 1},
  {task_id: 214, asignee_id: 6},
  {task_id: 214, asignee_id: 5},
  {task_id: 215, asignee_id: 1},
  {task_id: 215, asignee_id: 6},
  {task_id: 215, asignee_id: 5},
  {task_id: 216, asignee_id: 1},
  {task_id: 216, asignee_id: 5},
  {task_id: 216, asignee_id: 6},
  {task_id: 217, asignee_id: 14},
  {task_id: 217, asignee_id: 5},
  {task_id: 218, asignee_id: 14},
  {task_id: 218, asignee_id: 5},
  {task_id: 218, asignee_id: 14},
  {task_id: 218, asignee_id: 5},
  {task_id: 218, asignee_id: 14},
  {task_id: 218, asignee_id: 14},
  {task_id: 219, asignee_id: 14},
  {task_id: 220, asignee_id: 15},
  {task_id: 220, asignee_id: 9},
  {task_id: 221, asignee_id: 9},
  {task_id: 222, asignee_id: 5},
  {task_id: 223, asignee_id: 15},
  {task_id: 224, asignee_id: 5},
  {task_id: 225, asignee_id: 14},
  {task_id: 226, asignee_id: 14},
  {task_id: 227, asignee_id: 14},
  {task_id: 227, asignee_id: 14},
  {task_id: 227, asignee_id: 14},
  {task_id: 227, asignee_id: 14},
  {task_id: 227, asignee_id: 14},
  {task_id: 228, asignee_id: 14},
  {task_id: 240, asignee_id: 14}
])
MembershipRequest.create!([
  {requester_id: 5, requestee_id: 6, organization_id: 1},
  {requester_id: 5, requestee_id: 4, organization_id: 4},
  {requester_id: 5, requestee_id: 1, organization_id: 2},
  {requester_id: 5, requestee_id: 2, organization_id: 3},
  {requester_id: 5, requestee_id: 1, organization_id: 2},
  {requester_id: 5, requestee_id: 6, organization_id: 1},
  {requester_id: 5, requestee_id: 4, organization_id: 4},
  {requester_id: 5, requestee_id: 1, organization_id: 6},
  {requester_id: 17, requestee_id: 5, organization_id: 1},
  {requester_id: 18, requestee_id: 17, organization_id: 1},
  {requester_id: 18, requestee_id: 5, organization_id: 1}
])
Organization.create!([
  {title: "math"},
  {title: "physics"},
  {title: "philosophy"},
  {title: "machines"},
  {title: "history"},
  {title: "fun"}
])
OrganizationMembership.create!([
  {member_id: 1, organization_id: 2},
  {member_id: 6, organization_id: 1},
  {member_id: 4, organization_id: 4},
  {member_id: 1, organization_id: 6},
  {member_id: 2, organization_id: 5},
  {member_id: 2, organization_id: 3},
  {member_id: 5, organization_id: 3},
  {member_id: 5, organization_id: 2},
  {member_id: 5, organization_id: 6},
  {member_id: 5, organization_id: 4},
  {member_id: 5, organization_id: 4},
  {member_id: 5, organization_id: 1},
  {member_id: 5, organization_id: 1},
  {member_id: 17, organization_id: 1},
  {member_id: 17, organization_id: 1}
])
Project.create!([
  {title: "P != NP", description: "    No pressure", status: "it might take a while", progress: nil, due_date: nil, organization_id: 1, owner_id: 5},
  {title: "Set of All Sets", description: "    Prove whether such a things exists.", status: "Looking good", progress: nil, due_date: nil, organization_id: 1, owner_id: 5},
  {title: "Sizes of Infinity", description: "    Does infinity vary in size? What about the reals vs the rationals or the rationals vs the naturals", status: "", progress: nil, due_date: nil, organization_id: 1, owner_id: 5},
  {title: "Goldbach Conjecture", description: "    Prove it", status: "", progress: nil, due_date: nil, organization_id: 1, owner_id: 5},
  {title: "Spaghetti", description: "    Why does spaghetti almost always break into more than two pieces when bent?", status: "", progress: nil, due_date: nil, organization_id: 2, owner_id: 5},
  {title: "Matter to Energy", description: "    How can we convert matter to energy?", status: "", progress: nil, due_date: nil, organization_id: 2, owner_id: 5},
  {title: "Reverse Sprinkler", description: "    What happens when you reverse the flow on a rotating sprinkler? Does the rotation reverse?", status: "", progress: nil, due_date: nil, organization_id: 2, owner_id: 5},
  {title: "Mind", description: "    What are mental states? ", status: "", progress: nil, due_date: nil, organization_id: 3, owner_id: 5},
  {title: "Informative Identity", description: "    If \"a = b\" means that a and b are the SAME THING, how can the statement be informative? Shouldn't already know it if we know what a is?", status: "", progress: nil, due_date: nil, organization_id: 3, owner_id: 5},
  {title: "Unicorns", description: "    How does the sentence \"Unicorns don't exist\" have a meaning if 'unicorn' doesn't actually refer to anything?", status: "", progress: nil, due_date: nil, organization_id: 3, owner_id: 5},
  {title: "Deterministic Finite Automaton", description: "    make a simple machine that will define languages", status: "", progress: nil, due_date: nil, organization_id: 4, owner_id: 5},
  {title: "Pushdown Automaton", description: "    fancy-up DFA with a memory", status: "", progress: nil, due_date: nil, organization_id: 4, owner_id: 5},
  {title: "Turing Machine", description: "    Make a computer!", status: "Alan is carrying us", progress: nil, due_date: nil, organization_id: 4, owner_id: 5},
  {title: "test ownership", description: "    ", status: "", progress: nil, due_date: nil, organization_id: 2, owner_id: 5},
  {title: "Manifold", description: "    Making this site", status: "", progress: nil, due_date: nil, organization_id: 6, owner_id: 5},
  {title: "test", description: "    ", status: "", progress: nil, due_date: nil, organization_id: 2, owner_id: 5},
  {title: "test", description: "    ", status: "", progress: nil, due_date: nil, organization_id: 1, owner_id: 5}
])
ProjectMembershipNotification.create!([
  {project_id: 3, adder_id: 5, user_id: 15},
  {project_id: 2, adder_id: 5, user_id: 14},
  {project_id: 5, adder_id: 5, user_id: 7},
  {project_id: 5, adder_id: 5, user_id: 1},
  {project_id: 3, adder_id: 5, user_id: 9},
  {project_id: 8, adder_id: 5, user_id: 2},
  {project_id: 8, adder_id: 5, user_id: 13},
  {project_id: 11, adder_id: 5, user_id: 15},
  {project_id: 1, adder_id: 5, user_id: 17},
  {project_id: 5, adder_id: 5, user_id: 6},
  {project_id: 15, adder_id: 5, user_id: 5},
  {project_id: 1, adder_id: 5, user_id: 18}
])
Task.create!([
  {title: "asdf", parent_task_id: nil, description: "asdf", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 6},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 6},
  {title: "", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "hgfh", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "abstract it away", parent_task_id: nil, description: "let's get this over with so Richard will calm down", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "fdsa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 1},
  {title: "task", parent_task_id: nil, description: "description", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 1},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "2", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "3", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "4", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "test auto-complete", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "What are attrs?", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "gf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "spider", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 8},
  {title: "you got this", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "gfd", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "jhdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "a", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "a", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "this is it", parent_task_id: nil, description: "ljhgla uhdl", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "5", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "6", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "rsw", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "7", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "8", parent_task_id: nil, description: "gdfag", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "9", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "10", parent_task_id: nil, description: "10", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "gfsh", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "dha", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "kfkhgd", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "khgcjhfc", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "khgfkhg", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "1", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "test assignee display", parent_task_id: nil, description: "Richard", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "adsf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "asdfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "11", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "12", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "make task items complete upon first rendered", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "make projects complete upon first rendering", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "fix organization-to-project navigation", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "test", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "adsf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 15},
  {title: "13", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "14", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "15", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 5},
  {title: "2", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "test", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "a", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "3sag", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "hd", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "gaere", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "sghg", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 3},
  {title: "render", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "ljd", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "gref", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "fret", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "ahfa", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "laeh;be", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "asdf", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "asda", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: 2},
  {title: "test", parent_task_id: nil, description: "testing", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "prepend", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "dfha", parent_task_id: nil, description: "", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil},
  {title: "Zussamen", parent_task_id: nil, description: "Just to see", creator_id: 5, due_date: nil, completed: nil, date_completed: nil, project_id: nil}
])
TeamMembership.create!([
  {project_id: 1, member_id: 5},
  {project_id: 6, member_id: 5},
  {project_id: 3, member_id: 15},
  {project_id: 2, member_id: 14},
  {project_id: 5, member_id: 7},
  {project_id: 5, member_id: 1},
  {project_id: 3, member_id: 9},
  {project_id: 8, member_id: 2},
  {project_id: 8, member_id: 13},
  {project_id: 3, member_id: 5},
  {project_id: 5, member_id: 5},
  {project_id: 11, member_id: 15},
  {project_id: 1, member_id: 17},
  {project_id: 5, member_id: 6},
  {project_id: 15, member_id: 5},
  {project_id: 2, member_id: 5},
  {project_id: 1, member_id: 18}
])
User.create!([
  {fname: "Richard", mname: "Phillips", lname: "Feynman", email: "wattafeynman@gmail.com", session_token: "aHfJ2ov1ZZ6LY6Zpz4a-Mg", password_digest: "$2a$10$JZvnEj63Z6SF4VUrI5rIYOjT7i758XYOG3CuWUgFMXS4NpUNJzpRe", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_45/v1440489476/Richard_Feynman_Nobel_bhyzxq.jpg"},
  {fname: "Alan", mname: "Mathison", lname: "Turing", email: "aturing@gmail.com", session_token: "Ppbj-aWZ0KZzQAcxFD850g", password_digest: "$2a$10$rEX2fxIsJbSSRdeNwr29E.71YVu0cypg85nceSb8Qoa5XLSnF1Ta2", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440489464/AlanTuring_afxv2l.jpg"},
  {fname: "Paul", mname: "", lname: "Erdos", email: "perdos@gmail.com", session_token: "wPJTpNFVzPjcnTX6Qfpn9w", password_digest: "$2a$10$d2/YNM7CI3YYAM2tFAhAh.OSdKyS40afSjdeG8BdhXxYLc/mf3xjy", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440489461/about_erdos_ap3vmf.jpg"},
  {fname: "Robert", mname: "", lname: "Oppenheimer", email: "roppenheimer@gmail.com", session_token: "QHFH_acYrZjftw480umW6g", password_digest: "$2a$10$V60FuHA6ut1Pv08sTH/ugenhnnn8gbJoSiDhUpqJfOG6Qi.UB4QG2", img_url: nil},
  {fname: "Austin", mname: "David", lname: "David", email: "austindaviddavid", session_token: "uunaEDtYvmrxUd3LD9iqSA", password_digest: "$2a$10$0VkhtBfye5yLwpj6AuURAO8xn3lDidfXOLyojJSqeS.RJHOcyRxPa", img_url: nil},
  {fname: "Kurt", mname: "", lname: "Goedel", email: "kgoedel@gmail.com", session_token: "5Qv2LxynciciQmOVrPHIvg", password_digest: "$2a$10$ZLkzGhh024C833GdouZXF.zbsRJjnFyIs.6NVBl7QrHfhSgCTMmom", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_45/v1440489473/kurt_godel_r9ukll.jpg"},
  {fname: "Henri", mname: "", lname: "Poincare", email: "hpoincare@gmail.com", session_token: "EKMA4fM-UWSw7bs3_bTeAw", password_digest: "$2a$10$bXbrngQdAdxO3iycwaAlm..94M2a5iaDb86ynYiW1jynsduIt9SFi", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440489470/Henri_Poincar%C3%A9-2_dnesuv.jpg"},
  {fname: "Georg", mname: "", lname: "Cantor", email: "gcantor@gmail.com", session_token: "txe1rtsHZA9SeFbyHNMwfg", password_digest: "$2a$10$ZvYIkphBF2u42mpCM8KH8O6baoYJ1zMZ236HKbFNeMhrAlsjeXklq", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440489467/Georg_Cantor2_mwflna.jpg"},
  {fname: "Austin", mname: "Young", lname: "David", email: "ayd", session_token: "hclHSoj7444pfEteE7jt0g", password_digest: "$2a$10$zl3W3AiCr81Neoec4JFf5uf.XyCF.iTu/LPLt8vyYo.il0a.hKszy", img_url: nil},
  {fname: "Austin", mname: "David", lname: "Young", email: "austin@austinmail.com", session_token: "rhMqqBTdYN30NG3_BesA8A", password_digest: "$2a$10$cNW0BTHvJM8V80uDX4X8Iuj/BYrMrwxG8Y9tgjQiXOqLlBBTKVAKm", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_thumb,g_center,w_42/v1440898888/Austin_Young_pic_u7wmny.jpg"},
  {fname: "Gottlob", mname: "", lname: "Frege", email: "gfrege@gmail.com", session_token: "-MplA1JwRcjatFRJv1j0Wg", password_digest: "$2a$10$NMoCodn5VZTMKoVmAMm2mePMOQdH9uAjnu2y4NyPXvbC7RzBWNd1e", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440489444/220px-Young_frege_c1olqb.jpg"},
  {fname: "Wolf", mname: "", lname: "Johnson", email: "wolf@gmail.com", session_token: "jpaUvKUpftAXxkoSypipxw", password_digest: "$2a$10$loXtJc8jD6KKyREPUvPZQOPZhDClV/Q31WH3Rarq4yY84c/TTUFGS", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440547188/Grey_Wolf_Face_xhe7wb.jpg"},
  {fname: "Spider", mname: "", lname: "Brown", email: "spider@gmail.com", session_token: "AD98UZUS28vKmJQLge0E4Q", password_digest: "$2a$10$maW.hHJwqOZnKlzhuAoSOOu1Vv6N.s83rKHO1ZnSyk/EbUF3RvDWa", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440547181/spider_face_inf3y8.jpg"},
  {fname: "Fox", mname: "", lname: "Williams", email: "fox@gmail.com", session_token: "a4sJjpfem7MnPo0NFKYxUw", password_digest: "$2a$10$QskMqRDBcPIEwe3MKuoNAek6jiUS9dFTmPHu9N47fKvG6KUamOX5S", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440547178/fox_face_y5cloj.jpg"},
  {fname: "Elephant", mname: "", lname: "Davis", email: "elephant@gmail.com", session_token: "x7UH4ikPq2PZVIistpcwyw", password_digest: "$2a$10$2lTJiMLAgXjR3/yVt5rjMOODIxEA7lWyr1w5ys1SQZxXjngv9w.xC", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440547171/elephant_face_a2tncz.jpg"},
  {fname: "Alpaca", mname: "", lname: "Smith", email: "alpaca@gmail.com", session_token: "meGLsl-FGAAq1cKj0xf5Zw", password_digest: "$2a$10$QKFQ7hUSctHVTwcOqP7z3u8AKLeJmStSiWMK082NMDR0YGsoTIrCW", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440547167/alpaca_face_h1r4um.jpg"},
  {fname: "Coyote", mname: "", lname: "Smith", email: "coyote@gmail.com", session_token: "HUQyryhd7bfCNzxMRdy43Q", password_digest: "$2a$10$kYfGtV/3I3elxPcoXR2Ri.te65uViUDba27kFDC5nidbqiznPvKDq", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440547163/coyote_face_xcwnrf.jpg"},
  {fname: "Bertrand", mname: "Arthur", lname: "Russell", email: "brussel@gmail.com", session_token: "wPwrXgkWN5N5etldWuhgoQ", password_digest: "$2a$10$VcdBG2JtcitNWx.cPU8.ZeiRFsC/fAfAidkijdOd926HRjUIsdmza", img_url: "http://res.cloudinary.com/dlyzaubjo/image/upload/c_scale,w_50/v1440489457/23351-004-4286D6B7_o87yxn.jpg"}
])
Workspace.create!([
  {title: "Math Work", user_id: 5},
  {title: "Fun", user_id: 5},
  {title: "Philosophy", user_id: 5},
  {title: "Autocomplete", user_id: 5},
  {title: "math", user_id: 17},
  {title: "sdfg", user_id: 5},
  {title: "sdfgs", user_id: 5},
  {title: "Manifold", user_id: 5},
  {title: "Websites", user_id: 5},
  {title: "test", user_id: 5}
])
WorkspaceProjectMembership.create!([
  {project_id: 1, workspace_id: 1},
  {project_id: 6, workspace_id: 1},
  {project_id: 2, workspace_id: 1},
  {project_id: 11, workspace_id: 1},
  {project_id: 5, workspace_id: 1},
  {project_id: 8, workspace_id: 1},
  {project_id: 3, workspace_id: 1},
  {project_id: 10, workspace_id: 1},
  {project_id: 1, workspace_id: 2},
  {project_id: 3, workspace_id: 2},
  {project_id: 10, workspace_id: 3},
  {project_id: 2, workspace_id: 3},
  {project_id: 9, workspace_id: 3},
  {project_id: 1, workspace_id: 3},
  {project_id: 5, workspace_id: 3},
  {project_id: 11, workspace_id: 4},
  {project_id: 7, workspace_id: 4},
  {project_id: 15, workspace_id: 9},
  {project_id: 1, workspace_id: 9},
  {project_id: 16, workspace_id: 9},
  {project_id: 2, workspace_id: 2},
  {project_id: 5, workspace_id: 2}
])
